### ISSUE TITLE
Draft not found in the published posts

### ISSUE THREAD

**Issue by Pauloparakleto** [anansilva/blog-rails#47]
Steps to reproduce this error:
Create a post as admin without publishing it.
Go to Preview menu.
Try to show any draft clicking on the friendly id name.
The error does not happen when clicking in a published post friendly id.
![Screenshot from 2022-01-21 19-28-58](https://user-images.githubusercontent.com/52010485/150608926-c58e0cea-ad03-4a7d-afb2-b8d9cadc3a92.png)

**Comment by anansilva** [comment]
Thanks for raising this issue, Paulo! 

If we remove the 'published' scope from the posts, we are potentially allowing visitors to see 'draft' posts. They would have to have the link to it, so it can be a bit farfetched, but still, it's safer this way. 

What I've done is to use an existing helper called `link_to_post` that will redirect to an admin preview page if there is a `current_user`, otherwise, it will render the public `show` page. 

The fix is in this commit:
https://github.com/anansilva/blog-rails/commit/e150779df242818f606ebe839579f517814180fa
